<img src="https://dauphine.psl.eu/fileadmin/_processed_/9/2/csm_damier_logo_Dauphine_f7b37a1ff2.jpg" width="200" style="vertical-align:middle" /> <h1>Master 222: Introduction to Python - Session 3</h1>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Zaltarba/PSL_python_for_finance/blob/main/python_session_3.ipynb)

# The Pandas library

In this exercise, you will learn to use the pandas module. Pandas is a Python package specialized in data manipulation.

[For more information on pandas click here](http://pandas.pydata.org/)

To begin, you need to import the `pandas` module under the abbreviated name `pd`. Therefore, execute this preamble cell. NumPy will also be used.

In [205]:
# Importing necessary libraries
import pandas as pd
import numpy as np

## Exercice 1

A Series is a one-dimensional array with labels, that can hold any data type. The labels are referred to as the index. Its syntax is as follows: pd.Series(X) where X is a list or an array.  

1. Create a Series of 5 data points from a random list of numbers distributed between 0 and 1.

In [206]:
## Insert your code here
serie_1=pd.Series(np.random.rand(5))
serie_1

0    0.234475
1    0.784314
2    0.691103
3    0.834412
4    0.784487
dtype: float64

It is possible to specify the indices using the following syntax: pd.Series(X, index = Y) where X is the data list and Y is a list of associated indices.  

2. Create a Series of 4 data points, each with a value of 1, and specify the following list of indices: ['a', 'b', 'c', 'd'].

In [207]:
## Insert your code here
serie_1=pd.Series(np.ones(4),index=['a','b','c','d'])
serie_1

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

By using indices, you can access the data in the Series in the same way you access elements in a list.  
Slicing is also possible.

3. Create a variable named series_one and assign it a Series created from a list of 4 random numbers distributed between 0 and 1.
4. Use the list of indices from the previous question: ['a', 'b', 'c', 'd'].
5. Retrieve the first element of series_one using the corresponding index.

In [208]:
## Insert your code here
series_one=pd.Series(np.random.rand(4), index=['a','b','c','d'])
first_element=series_one['a']
print(series_one)
print(first_element)

a    0.041950
b    0.832551
c    0.026138
d    0.370653
dtype: float64
0.04194966033223979

6. Change the fourth data point of `series_un` to 0.
7. Display `series_un`.

In [209]:
## Insert your code here
series_one['a']=0
series_one

a    0.000000
b    0.832551
c    0.026138
d    0.370653
dtype: float64

## Exercice 2

Python consistently returns a `dtype: float64` when calling the Series. This represents the data type, in this case floats, and their encoding, here on 64 bits. You can specify the data type you want to handle when creating a Series.

Furthermore, you can name the Series using the `name` parameter.

1. Create a variable `series_two` from an array of four ones.
2. Specify the data type `dtype` as `int`.
3. Name this Series `my_series`.
4. Display the Series.

In [210]:
## Insert your code here
series_two=pd.Series(np.ones(4), dtype="int", name="my_series")
series_two

0    1
1    1
2    1
3    1
Name: my_series, dtype: int64

The `describe()` function returns a variety of information about the Series it is applied to.

5. Create a variable `series_three` from an array of 20 random numbers uniformly distributed between 0 and 1.
6. Display information about the Series using `describe()`.

In [211]:
## Insert your code here
series_three=pd.Series(np.random.rand(20))
pd.DataFrame.describe(series_three)

count    20.000000
mean      0.544292
std       0.258003
min       0.025311
25%       0.380131
50%       0.537201
75%       0.720722
max       0.962017
dtype: float64

It's possible to add Series together. Pandas will sum the data with matching *indices*. If an *index* is missing in one of the Series, the resulting sum Series will display `NaN` (Not a Number) at that index.

7. Create a Series `series_four` from an array of 19 random numbers uniformly distributed between 0 and 1.
8. Sum `series_three` and `series_four` and look at the result.

In [212]:
## Insert your code here
series_four=pd.Series(np.random.rand(19))
series_three+series_four

0     0.769012
1     1.019871
2     1.093065
3     1.275283
4     0.608296
5     0.977526
6     1.436005
7     0.935790
8     0.307594
9     1.292640
10    1.171924
11    0.572754
12    1.361621
13    1.031202
14    1.073019
15    1.150682
16    0.979500
17    1.065235
18    1.694961
19         NaN
dtype: float64

However, you can specify a particular value to use where the *indices* do not match during a summation. The following syntax is used:
```
## Assume a and b are two Series
a.add(b, fill_value = 0)  ## we decide to replace with 0
```

9. Sum `series_three` and `series_four` by specifying fill_value equal to 100.

In [213]:
## Insert your code here
series_three.add(series_four, fill_value=100)

0       0.769012
1       1.019871
2       1.093065
3       1.275283
4       0.608296
5       0.977526
6       1.436005
7       0.935790
8       0.307594
9       1.292640
10      1.171924
11      0.572754
12      1.361621
13      1.031202
14      1.073019
15      1.150682
16      0.979500
17      1.065235
18      1.694961
19    100.753368
dtype: float64

Lastly, it's possible to use mathematical operators on Series. The following syntax is used:
```
# Assume a is a Series
a[a >= 0.5]  ## returns the data from a greater than 0.5
a * 2  ## multiplies the data from a by two
```

10. Create a variable `a`, and assign it a Series of integer numbers uniformly distributed between 1 and 20, with a size of 20.
11. Display the Series with data strictly greater than 10.

In [214]:
## Insert your code here
a=pd.Series(np.random.randint(1,21,20))
a[a>10]

1     14
2     15
3     17
5     12
6     18
7     17
8     19
10    17
17    19
19    17
dtype: int64

## Exercice 3

1. Create an *index* of size 20 that includes "boy" or "girl" randomly distributed.
    - use a list by comprehension
2. Create an array of size 20 that displays ages ranging from 3 to 16 years, randomly distributed.
3. Create a Series `cousins` with `name = "my cousins"`, the index created previously, and data from the array.
4. Using the index, create a Series boys and a Series girls filtering the Series `cousins`.
    - use `cousins.index`
5. Display information about these two Series.

In [215]:
## Insert your code here
r=np.random.randint(0,2,20)
index=['boy' if x==0 else 'girl' for x in r]
ages=np.random.randint(3,17,20)

cousins=pd.Series(ages, index=index, name='my_cousins')

boys=cousins[cousins.index=='boy']
girls=cousins[cousins.index=='girl']

print(boys)
print(girls)

boy    14
boy    12
boy    10
boy    12
boy    10
boy    15
boy    10
boy    15
boy     3
boy    14
boy    10
boy     5
boy     5
Name: my_cousins, dtype: int64
girl    14
girl     9
girl     4
girl     7
girl     9
girl     4
girl     9
Name: my_cousins, dtype: int64

## Exercice 4

Now we turn our attention to DataFrames. DataFrames are the two-dimensional extension of Series. Thus, the *indices* are shared among the columns of the DataFrame.

A common way to create a DataFrame is by using a dictionary. The syntax is as follows:
```python
pd.DataFrame({'Name of the first column': data_1, 'Name of the second column': data_2})
```
1. Create a DataFrame *df* with two columns: 'Gender' and 'Age', using the data from the previous question.
2. Display the DataFrame.

In [216]:
## Insert your code here
df_1=pd.DataFrame({'Gender':index, 'Age':ages})
df_1

   Gender  Age
0    girl   14
1    girl    9
2     boy   14
3     boy   12
4     boy   10
5     boy   12
6    girl    4
7     boy   10
8     boy   15
9     boy   10
10    boy   15
11   girl    7
12   girl    9
13    boy    3
14   girl    4
15    boy   14
16    boy   10
17   girl    9
18    boy    5
19    boy    5

3. Create a list *dominant_hand* of size 20 that contains "left-handed" or "right-handed" distributed randomly.
    - Use a list by comprehension
4. Add this list as a new column to *df*.  
    - Use `df['Dominant_hand'] = dominant_hand`
    - When naming columns avoid putting spaces, use _ instead

In [217]:
## Insert your code here
r=np.random.randint(0,2,20)
dominant_hand=['left-handed' if x==0 else 'right-handed' for x in r]
df_1['Dominant hand']=dominant_hand
df_1

   Gender  Age Dominant hand
0    girl   14  right-handed
1    girl    9  right-handed
2     boy   14  right-handed
3     boy   12   left-handed
4     boy   10  right-handed
5     boy   12   left-handed
6    girl    4  right-handed
7     boy   10  right-handed
8     boy   15  right-handed
9     boy   10  right-handed
10    boy   15  right-handed
11   girl    7   left-handed
12   girl    9  right-handed
13    boy    3  right-handed
14   girl    4   left-handed
15    boy   14   left-handed
16    boy   10  right-handed
17   girl    9  right-handed
18    boy    5  right-handed
19    boy    5   left-handed

*Slicing* is possible with DataFrames.

5. Display the first 5 rows of *data_one*.
    - Using slicing
    - Using .head() method

In [218]:
## Insert your code here
df_1.head(5)

  Gender  Age Dominant hand
0   girl   14  right-handed
1   girl    9  right-handed
2    boy   14  right-handed
3    boy   12   left-handed
4    boy   10  right-handed

In [219]:
df_1.iloc[:5,:]

  Gender  Age Dominant hand
0   girl   14  right-handed
1   girl    9  right-handed
2    boy   14  right-handed
3    boy   12   left-handed
4    boy   10  right-handed

6. Display the columns "Gender" and "Dominant Hand".

In [220]:
## Insert your code here
df_1[['Gender','Dominant hand']]

   Gender Dominant hand
0    girl  right-handed
1    girl  right-handed
2     boy  right-handed
3     boy   left-handed
4     boy  right-handed
5     boy   left-handed
6    girl  right-handed
7     boy  right-handed
8     boy  right-handed
9     boy  right-handed
10    boy  right-handed
11   girl   left-handed
12   girl  right-handed
13    boy  right-handed
14   girl   left-handed
15    boy   left-handed
16    boy  right-handed
17   girl  right-handed
18    boy  right-handed
19    boy   left-handed

## Exercice 5

It is possible to concatenate two DataFrames using the command `pd.concat()`. The syntax is as follows:
```python
# Assume X and Y are two DataFrames
pd.concat([X,Y], axis = 0)  ## concatenates vertically
pd.concat([X,Y], axis = 1)  ## concatenates horizontally
```
1. Create a list of size 20 that includes "red", "blue", or "green" distributed randomly.
    - use a list by comprehension
    - use a dictionnary
    - use np.random.randint
2. Create a DataFrame df_colors from this list.
3. Add a name to the column using the command df_colors.columns = ['Column_Name'].
4. Concatenate df and df_colors into df.

In [221]:
## Insert your code here
r=np.random.randint(0,3,20)
colors=['red' if x==0 else('blue' if x==1 else 'green') for x in r]
df_colors=pd.DataFrame({'Colors':colors})
pd.concat([df_1, df_colors], axis=1)

   Gender  Age Dominant hand Colors
0    girl   14  right-handed   blue
1    girl    9  right-handed   blue
2     boy   14  right-handed    red
3     boy   12   left-handed   blue
4     boy   10  right-handed    red
5     boy   12   left-handed   blue
6    girl    4  right-handed  green
7     boy   10  right-handed    red
8     boy   15  right-handed  green
9     boy   10  right-handed    red
10    boy   15  right-handed    red
11   girl    7   left-handed    red
12   girl    9  right-handed  green
13    boy    3  right-handed  green
14   girl    4   left-handed  green
15    boy   14   left-handed   blue
16    boy   10  right-handed  green
17   girl    9  right-handed    red
18    boy    5  right-handed   blue
19    boy    5   left-handed  green

## To Go Further

Use pandas documentations or stackoverflow to find the answers of the following exercises.

### Basic DataFrame Operations:

1. Create a DataFrame from a dictionary with keys: 'Name', 'Age', 'City' and populate it with some data.
2. Display the first 5 rows of the DataFrame.
3. Display the last 3 rows of the DataFrame.
4. Display the data types of each column.

### Indexing and Selection:

1. Select the 'Name' and 'City' columns from the DataFrame.
2. Select the row at index 2 from the DataFrame.
3. Select the rows where 'Age' is greater than 25. Display the first 5.

### Sorting and Ranking:

1. Sort the DataFrame based on 'Age' in descending order.
2. Create a variable 'Age_rank', with the oldest as rank 1.

### Missing Data:

1. Introduce some missing values in the DataFrame using np.nan.
    - Create a dataframe using a dictionnary by comprehension
    - Do not add missing values to the column Name
2. Display the number of missing values for each columns
3. Fill the missing values with the mean of the non-missing values.

### Grouping and Aggregation:

1. Group the DataFrame by 'City' and calculate the mean age for each city.
2. Find the maximum and minimum age for each city.
3. Create a variable 'Age_rank_by_city', creating a ranking for each city.

### Merging, Joining, and Concatenating:

1. Create a second DataFrame with keys: 'Name', 'Job Title'.
2. Merge the two DataFrames.
    - Use df.merge

In [222]:
## Insert your code here
"""
Basic DataFrame Operations:
Create a DataFrame from a dictionary with keys: 'Name', 'Age', 'City' and populate it with some data.
Display the first 5 rows of the DataFrame.
Display the last 3 rows of the DataFrame.
Display the data types of each column.
"""

names_list = [
    "Thomas",
    "Camille",
    "Lucas",
    "Sarah",
    "Antoine",
    "Chloé",
    "Nicolas",
    "Manon",
    "Maxime",
    "Julie"
]
cities_list = [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille"
]
names=np.random.choice(names_list,35)
ages=np.random.randint(0,101,35)
cities=np.random.choice(cities_list,35)

df_1=pd.DataFrame({'Name':names, 'Age':ages, 'City':cities})

In [223]:
df_1.head(5)

      Name  Age         City
0  Nicolas   99        Paris
1  Camille    5    Marseille
2  Nicolas   46  Montpellier
3   Maxime   15    Marseille
4    Lucas   94        Paris

In [224]:
df_1.tail(3)

      Name  Age      City
32  Maxime   16     Lille
33   Julie   41  Toulouse
34  Maxime   69      Lyon

In [225]:
df_1.dtypes

Name    object
Age      int64
City    object
dtype: object

In [226]:
"""
Indexing and Selection:
Select the 'Name' and 'City' columns from the DataFrame.
Select the row at index 2 from the DataFrame.
Select the rows where 'Age' is greater than 25. Display the first 5.
"""

df_1['Name']

0     Nicolas
1     Camille
2     Nicolas
3      Maxime
4       Lucas
5       Lucas
6       Julie
7     Nicolas
8      Thomas
9       Lucas
10     Thomas
11     Thomas
12      Sarah
13     Maxime
14      Julie
15     Thomas
16      Sarah
17      Lucas
18      Lucas
19      Manon
20     Thomas
21    Camille
22    Camille
23     Maxime
24      Chloé
25      Lucas
26    Antoine
27     Thomas
28      Lucas
29    Camille
30    Nicolas
31     Maxime
32     Maxime
33      Julie
34     Maxime
Name: Name, dtype: object

In [227]:
df_1.iloc[2]

Name        Nicolas
Age              46
City    Montpellier
Name: 2, dtype: object

In [228]:
df_1[df_1['Age']>25].head(5)

      Name  Age         City
0  Nicolas   99        Paris
2  Nicolas   46  Montpellier
4    Lucas   94        Paris
5    Lucas   63  Montpellier
6    Julie   66   Strasbourg

In [229]:
"""
Sorting and Ranking:
Sort the DataFrame based on 'Age' in descending order.
Create a variable 'Age_rank', with the oldest as rank 1.
"""

df_1_sorted=df_1.sort_values('Age', ascending=False)
age_rank=df_1_sorted['Age'].rank(ascending=False, method='min')
df_1_sorted['Age rank']=age_rank
pd.concat((df_1, df_1_sorted['Age rank']),axis=1)

       Name  Age         City  Age rank
0   Nicolas   99        Paris       1.0
1   Camille    5    Marseille      34.0
2   Nicolas   46  Montpellier      21.0
3    Maxime   15    Marseille      28.0
4     Lucas   94        Paris       5.0
5     Lucas   63  Montpellier      12.0
6     Julie   66   Strasbourg      11.0
7   Nicolas   60     Bordeaux      14.0
8    Thomas   90     Bordeaux       6.0
9     Lucas   63   Strasbourg      12.0
10   Thomas   50         Nice      18.0
11   Thomas   58         Nice      15.0
12    Sarah   36         Lyon      26.0
13   Maxime    1     Bordeaux      35.0
14    Julie   12         Lyon      31.0
15   Thomas   40        Lille      24.0
16    Sarah   96         Lyon       4.0
17    Lucas   37        Lille      25.0
18    Lucas   99        Paris       1.0
19    Manon    9  Montpellier      33.0
20   Thomas   15     Bordeaux      28.0
21  Camille   41        Lille      22.0
22  Camille   14     Bordeaux      30.0
23   Maxime   55       Nantes      16.0
24    Chloé   76   Strasbourg       7.0
25    Lucas   10         Lyon      32.0
26  Antoine   74     Toulouse       9.0
27   Thomas   50     Toulouse      18.0
28    Lucas   48  Montpellier      20.0
29  Camille   97        Paris       3.0
30  Nicolas   76     Bordeaux       7.0
31   Maxime   51     Bordeaux      17.0
32   Maxime   16        Lille      27.0
33    Julie   41     Toulouse      22.0
34   Maxime   69         Lyon      10.0

In [230]:
"""
Missing Data:
Introduce some missing values in the DataFrame using np.nan.
Create a dataframe using a dictionnary by comprehension
Do not add missing values to the column Name
Display the number of missing values for each columns
Fill the missing values with the mean of the non-missing values.
"""
df_2=df_1.copy()
df_2['Age'].iloc[4:11]=np.nan
df_2['Age']=df_2['Age'].fillna(df_2['Age'].mean())
df_2

/tmp/ipykernel_3451/771034224.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_2['Age'].iloc[4:11]=np.nan
/tmp/ipykernel_3451/771034224.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Age'].iloc[4:11]=np.nan

       Name        Age         City
0   Nicolas  99.000000        Paris
1   Camille   5.000000    Marseille
2   Nicolas  46.000000  Montpellier
3    Maxime  15.000000    Marseille
4     Lucas  45.928571        Paris
5     Lucas  45.928571  Montpellier
6     Julie  45.928571   Strasbourg
7   Nicolas  45.928571     Bordeaux
8    Thomas  45.928571     Bordeaux
9     Lucas  45.928571   Strasbourg
10   Thomas  45.928571         Nice
11   Thomas  58.000000         Nice
12    Sarah  36.000000         Lyon
13   Maxime   1.000000     Bordeaux
14    Julie  12.000000         Lyon
15   Thomas  40.000000        Lille
16    Sarah  96.000000         Lyon
17    Lucas  37.000000        Lille
18    Lucas  99.000000        Paris
19    Manon   9.000000  Montpellier
20   Thomas  15.000000     Bordeaux
21  Camille  41.000000        Lille
22  Camille  14.000000     Bordeaux
23   Maxime  55.000000       Nantes
24    Chloé  76.000000   Strasbourg
25    Lucas  10.000000         Lyon
26  Antoine  74.000000     Toulouse
27   Thomas  50.000000     Toulouse
28    Lucas  48.000000  Montpellier
29  Camille  97.000000        Paris
30  Nicolas  76.000000     Bordeaux
31   Maxime  51.000000     Bordeaux
32   Maxime  16.000000        Lille
33    Julie  41.000000     Toulouse
34   Maxime  69.000000         Lyon

In [245]:
"""
Grouping and Aggregation:
Group the DataFrame by 'City' and calculate the mean age for each city.
Find the maximum and minimum age for each city.
Create a variable 'Age_rank_by_city', creating a ranking for each city.
"""
df_3 = df_1.groupby('City').agg(
    Mean=('Age', 'mean'),
    Max=('Age', 'max'),
    Min=('Age', 'min')
)

df_3['Age rank']=df_3['Mean'].rank(ascending=False)
df_3

                  Mean  Max  Min  Age rank
City
Bordeaux     43.857143   90    1       7.0
Lille        33.500000   41   16       9.0
Lyon         44.600000   96   10       6.0
Marseille    10.000000   15    5      10.0
Montpellier  41.500000   63    9       8.0
Nantes       55.000000   55   55       3.5
Nice         54.000000   58   50       5.0
Paris        97.250000   99   94       1.0
Strasbourg   68.333333   76   63       2.0
Toulouse     55.000000   74   41       3.5

In [247]:
"""
Merging, Joining, and Concatenating:
Create a second DataFrame with keys: 'Name', 'Job Title'.
Merge the two DataFrames.
Use df.merge
"""
jobs_list = [
    "Data Scientist",
    "Analyste financier",
    "Ingénieur en Intelligence Artificielle",
    "Architecte logiciel",
    "Chef de projet",
    "Consultant en stratégie",
    "UX/UI Designer",
    "Médecin généraliste",
    "Avocat d'affaires",
    "Expert-comptable"
]

jobs=np.random.choice(jobs_list,35)
df_4=pd.DataFrame({'Name':names, 'Job':jobs})
df_result = df_4.merge(df_1, left_index=True, right_index=True)
df_result

        Name                      Job  Age         City
0    Nicolas      Médecin généraliste   99        Paris
1    Nicolas      Médecin généraliste   46  Montpellier
2    Nicolas      Médecin généraliste   60     Bordeaux
3    Nicolas      Médecin généraliste   76     Bordeaux
4    Camille        Avocat d'affaires    5    Marseille
..       ...                      ...  ...          ...
164   Maxime  Consultant en stratégie    1     Bordeaux
165   Maxime  Consultant en stratégie   55       Nantes
166   Maxime  Consultant en stratégie   51     Bordeaux
167   Maxime  Consultant en stratégie   16        Lille
168   Maxime  Consultant en stratégie   69         Lyon

[169 rows x 4 columns]