<img src="https://dauphine.psl.eu/fileadmin/_processed_/9/2/csm_damier_logo_Dauphine_f7b37a1ff2.jpg" width="200" style="vertical-align:middle" /> <h1>Master 222: Introduction to Python - Session 3</h1>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Zaltarba/PSL_python_for_finance/blob/main/python_session_3.ipynb)

# The Pandas library

In this exercise, you will learn to use the pandas module. Pandas is a Python package specialized in data manipulation.

[For more information on pandas click here](http://pandas.pydata.org/)

To begin, you need to import the `pandas` module under the abbreviated name `pd`. Therefore, execute this preamble cell. NumPy will also be used.

In [148]:
# Importing necessary libraries
import pandas as pd
import numpy as np

## Exercice 1

A Series is a one-dimensional array with labels, that can hold any data type. The labels are referred to as the index. Its syntax is as follows: pd.Series(X) where X is a list or an array.  

1. Create a Series of 5 data points from a random list of numbers distributed between 0 and 1.

In [149]:
## Insert your code here
serie_1=pd.Series(np.random.rand(5))
serie_1

0    0.531414
1    0.998371
2    0.750528
3    0.825778
4    0.818378
dtype: float64

It is possible to specify the indices using the following syntax: pd.Series(X, index = Y) where X is the data list and Y is a list of associated indices.  

2. Create a Series of 4 data points, each with a value of 1, and specify the following list of indices: ['a', 'b', 'c', 'd'].

In [150]:
## Insert your code here
serie_1=pd.Series(np.ones(4),index=['a','b','c','d'])
serie_1

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

By using indices, you can access the data in the Series in the same way you access elements in a list.  
Slicing is also possible.

3. Create a variable named series_one and assign it a Series created from a list of 4 random numbers distributed between 0 and 1.
4. Use the list of indices from the previous question: ['a', 'b', 'c', 'd'].
5. Retrieve the first element of series_one using the corresponding index.

In [151]:
## Insert your code here
series_one=pd.Series(np.random.rand(4), index=['a','b','c','d'])
first_element=series_one['a']
print(series_one)
print(first_element)

a    0.042088
b    0.825414
c    0.404506
d    0.779719
dtype: float64
0.04208786350926874

6. Change the fourth data point of `series_un` to 0.
7. Display `series_un`.

In [152]:
## Insert your code here
series_one['a']=0
series_one

a    0.000000
b    0.825414
c    0.404506
d    0.779719
dtype: float64

## Exercice 2

Python consistently returns a `dtype: float64` when calling the Series. This represents the data type, in this case floats, and their encoding, here on 64 bits. You can specify the data type you want to handle when creating a Series.

Furthermore, you can name the Series using the `name` parameter.

1. Create a variable `series_two` from an array of four ones.
2. Specify the data type `dtype` as `int`.
3. Name this Series `my_series`.
4. Display the Series.

In [153]:
## Insert your code here
series_two=pd.Series(np.ones(4), dtype="int", name="my_series")
series_two

0    1
1    1
2    1
3    1
Name: my_series, dtype: int64

The `describe()` function returns a variety of information about the Series it is applied to.

5. Create a variable `series_three` from an array of 20 random numbers uniformly distributed between 0 and 1.
6. Display information about the Series using `describe()`.

In [154]:
## Insert your code here
series_three=pd.Series(np.random.rand(20))
pd.DataFrame.describe(series_three)

count    20.000000
mean      0.481398
std       0.297012
min       0.003130
25%       0.237222
50%       0.532927
75%       0.734862
max       0.899935
dtype: float64

It's possible to add Series together. Pandas will sum the data with matching *indices*. If an *index* is missing in one of the Series, the resulting sum Series will display `NaN` (Not a Number) at that index.

7. Create a Series `series_four` from an array of 19 random numbers uniformly distributed between 0 and 1.
8. Sum `series_three` and `series_four` and look at the result.

In [155]:
## Insert your code here
series_four=pd.Series(np.random.rand(19))
series_three+series_four

0     0.879163
1     0.529869
2     1.515821
3     0.332027
4     1.644063
5     1.182821
6     0.872535
7     0.524401
8     0.715947
9     1.375732
10    1.341245
11    1.030649
12    1.176227
13    0.958684
14    1.358535
15    0.201015
16    1.166091
17    1.098346
18    1.226958
19         NaN
dtype: float64

However, you can specify a particular value to use where the *indices* do not match during a summation. The following syntax is used:
```
## Assume a and b are two Series
a.add(b, fill_value = 0)  ## we decide to replace with 0
```

9. Sum `series_three` and `series_four` by specifying fill_value equal to 100.

In [156]:
## Insert your code here
series_three.add(series_four, fill_value=100)

0       0.879163
1       0.529869
2       1.515821
3       0.332027
4       1.644063
5       1.182821
6       0.872535
7       0.524401
8       0.715947
9       1.375732
10      1.341245
11      1.030649
12      1.176227
13      0.958684
14      1.358535
15      0.201015
16      1.166091
17      1.098346
18      1.226958
19    100.346143
dtype: float64

Lastly, it's possible to use mathematical operators on Series. The following syntax is used:
```
# Assume a is a Series
a[a >= 0.5]  ## returns the data from a greater than 0.5
a * 2  ## multiplies the data from a by two
```

10. Create a variable `a`, and assign it a Series of integer numbers uniformly distributed between 1 and 20, with a size of 20.
11. Display the Series with data strictly greater than 10.

In [157]:
## Insert your code here
a=pd.Series(np.random.randint(1,21,20))
a[a>10]

2     19
3     17
4     15
5     19
8     13
11    15
17    12
18    13
19    11
dtype: int64

## Exercice 3

1. Create an *index* of size 20 that includes "boy" or "girl" randomly distributed.
    - use a list by comprehension
2. Create an array of size 20 that displays ages ranging from 3 to 16 years, randomly distributed.
3. Create a Series `cousins` with `name = "my cousins"`, the index created previously, and data from the array.
4. Using the index, create a Series boys and a Series girls filtering the Series `cousins`.
    - use `cousins.index`
5. Display information about these two Series.

In [158]:
## Insert your code here
r=np.random.randint(0,2,20)
index=['boy' if x==0 else 'girl' for x in r]
ages=np.random.randint(3,17,20)

cousins=pd.Series(ages, index=index, name='my_cousins')

boys=cousins[cousins.index=='boy']
girls=cousins[cousins.index=='girl']

print(boys)
print(girls)

boy     8
boy     7
boy     4
boy     8
boy    10
boy    15
boy    10
boy     3
boy    16
boy    12
boy     5
boy     4
Name: my_cousins, dtype: int64
girl    15
girl     9
girl     4
girl    15
girl    12
girl     3
girl    11
girl    13
Name: my_cousins, dtype: int64

## Exercice 4

Now we turn our attention to DataFrames. DataFrames are the two-dimensional extension of Series. Thus, the *indices* are shared among the columns of the DataFrame.

A common way to create a DataFrame is by using a dictionary. The syntax is as follows:
```python
pd.DataFrame({'Name of the first column': data_1, 'Name of the second column': data_2})
```
1. Create a DataFrame *df* with two columns: 'Gender' and 'Age', using the data from the previous question.
2. Display the DataFrame.

In [159]:
## Insert your code here
df_1=pd.DataFrame({'Gender':index, 'Age':ages})
df_1

   Gender  Age
0     boy    8
1     boy    7
2     boy    4
3    girl   15
4     boy    8
5    girl    9
6    girl    4
7     boy   10
8     boy   15
9    girl   15
10    boy   10
11   girl   12
12    boy    3
13    boy   16
14    boy   12
15   girl    3
16   girl   11
17    boy    5
18    boy    4
19   girl   13

3. Create a list *dominant_hand* of size 20 that contains "left-handed" or "right-handed" distributed randomly.
    - Use a list by comprehension
4. Add this list as a new column to *df*.  
    - Use `df['Dominant_hand'] = dominant_hand`
    - When naming columns avoid putting spaces, use _ instead

In [160]:
## Insert your code here
r=np.random.randint(0,2,20)
dominant_hand=['left-handed' if x==0 else 'right-handed' for x in r]
df_1['Dominant hand']=dominant_hand
df_1

   Gender  Age Dominant hand
0     boy    8  right-handed
1     boy    7   left-handed
2     boy    4   left-handed
3    girl   15  right-handed
4     boy    8  right-handed
5    girl    9  right-handed
6    girl    4   left-handed
7     boy   10  right-handed
8     boy   15   left-handed
9    girl   15  right-handed
10    boy   10   left-handed
11   girl   12  right-handed
12    boy    3  right-handed
13    boy   16  right-handed
14    boy   12   left-handed
15   girl    3  right-handed
16   girl   11   left-handed
17    boy    5   left-handed
18    boy    4  right-handed
19   girl   13  right-handed

*Slicing* is possible with DataFrames.

5. Display the first 5 rows of *data_one*.
    - Using slicing
    - Using .head() method

In [161]:
## Insert your code here
df_1.head(5)

  Gender  Age Dominant hand
0    boy    8  right-handed
1    boy    7   left-handed
2    boy    4   left-handed
3   girl   15  right-handed
4    boy    8  right-handed

In [162]:
df_1.iloc[:5,:]

  Gender  Age Dominant hand
0    boy    8  right-handed
1    boy    7   left-handed
2    boy    4   left-handed
3   girl   15  right-handed
4    boy    8  right-handed

6. Display the columns "Gender" and "Dominant Hand".

In [163]:
## Insert your code here
df_1[['Gender','Dominant hand']]

   Gender Dominant hand
0     boy  right-handed
1     boy   left-handed
2     boy   left-handed
3    girl  right-handed
4     boy  right-handed
5    girl  right-handed
6    girl   left-handed
7     boy  right-handed
8     boy   left-handed
9    girl  right-handed
10    boy   left-handed
11   girl  right-handed
12    boy  right-handed
13    boy  right-handed
14    boy   left-handed
15   girl  right-handed
16   girl   left-handed
17    boy   left-handed
18    boy  right-handed
19   girl  right-handed

## Exercice 5

It is possible to concatenate two DataFrames using the command `pd.concat()`. The syntax is as follows:
```python
# Assume X and Y are two DataFrames
pd.concat([X,Y], axis = 0)  ## concatenates vertically
pd.concat([X,Y], axis = 1)  ## concatenates horizontally
```
1. Create a list of size 20 that includes "red", "blue", or "green" distributed randomly.
    - use a list by comprehension
    - use a dictionnary
    - use np.random.randint
2. Create a DataFrame df_colors from this list.
3. Add a name to the column using the command df_colors.columns = ['Column_Name'].
4. Concatenate df and df_colors into df.

In [164]:
## Insert your code here
r=np.random.randint(0,3,20)
colors=['red' if x==0 else('blue' if x==1 else 'green') for x in r]
df_colors=pd.DataFrame({'Colors':colors})
pd.concat([df_1, df_colors], axis=1)

   Gender  Age Dominant hand Colors
0     boy    8  right-handed   blue
1     boy    7   left-handed   blue
2     boy    4   left-handed  green
3    girl   15  right-handed    red
4     boy    8  right-handed   blue
5    girl    9  right-handed  green
6    girl    4   left-handed   blue
7     boy   10  right-handed   blue
8     boy   15   left-handed   blue
9    girl   15  right-handed  green
10    boy   10   left-handed   blue
11   girl   12  right-handed    red
12    boy    3  right-handed   blue
13    boy   16  right-handed    red
14    boy   12   left-handed  green
15   girl    3  right-handed   blue
16   girl   11   left-handed  green
17    boy    5   left-handed   blue
18    boy    4  right-handed  green
19   girl   13  right-handed   blue

## To Go Further

Use pandas documentations or stackoverflow to find the answers of the following exercises.

### Basic DataFrame Operations:

1. Create a DataFrame from a dictionary with keys: 'Name', 'Age', 'City' and populate it with some data.
2. Display the first 5 rows of the DataFrame.
3. Display the last 3 rows of the DataFrame.
4. Display the data types of each column.

### Indexing and Selection:

1. Select the 'Name' and 'City' columns from the DataFrame.
2. Select the row at index 2 from the DataFrame.
3. Select the rows where 'Age' is greater than 25. Display the first 5.

### Sorting and Ranking:

1. Sort the DataFrame based on 'Age' in descending order.
2. Create a variable 'Age_rank', with the oldest as rank 1.

### Missing Data:

1. Introduce some missing values in the DataFrame using np.nan.
    - Create a dataframe using a dictionnary by comprehension
    - Do not add missing values to the column Name
2. Display the number of missing values for each columns
3. Fill the missing values with the mean of the non-missing values.

### Grouping and Aggregation:

1. Group the DataFrame by 'City' and calculate the mean age for each city.
2. Find the maximum and minimum age for each city.
3. Create a variable 'Age_rank_by_city', creating a ranking for each city.

### Merging, Joining, and Concatenating:

1. Create a second DataFrame with keys: 'Name', 'Job Title'.
2. Merge the two DataFrames.
    - Use df.merge

In [165]:
## Insert your code here
"""
Basic DataFrame Operations:
Create a DataFrame from a dictionary with keys: 'Name', 'Age', 'City' and populate it with some data.
Display the first 5 rows of the DataFrame.
Display the last 3 rows of the DataFrame.
Display the data types of each column.
"""

names_list = [
    "Thomas",
    "Camille",
    "Lucas",
    "Sarah",
    "Antoine",
    "Chloé",
    "Nicolas",
    "Manon",
    "Maxime",
    "Julie"
]
cities_list = [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille"
]
names=np.random.choice(names_list,35)
ages=np.random.randint(0,101,35)
cities=np.random.choice(cities_list,35)

df_1=pd.DataFrame({'Name':names, 'Age':ages, 'City':cities})

In [166]:
df_1.head(5)

      Name  Age         City
0   Thomas   58         Lyon
1    Sarah   37       Nantes
2  Camille   69  Montpellier
3   Thomas   15        Lille
4  Antoine   91         Nice

In [167]:
df_1.tail(3)

       Name  Age      City
32  Nicolas   75      Lyon
33    Sarah   86  Bordeaux
34   Maxime   72     Lille

In [168]:
df_1.dtypes

Name    object
Age      int64
City    object
dtype: object

In [169]:
"""
Indexing and Selection:
Select the 'Name' and 'City' columns from the DataFrame.
Select the row at index 2 from the DataFrame.
Select the rows where 'Age' is greater than 25. Display the first 5.
"""

df_1['Name']

0      Thomas
1       Sarah
2     Camille
3      Thomas
4     Antoine
5     Nicolas
6      Thomas
7     Antoine
8       Sarah
9     Antoine
10      Julie
11      Lucas
12     Maxime
13      Lucas
14    Camille
15    Antoine
16      Lucas
17      Sarah
18      Julie
19     Maxime
20      Chloé
21      Chloé
22      Lucas
23     Thomas
24    Camille
25    Antoine
26      Julie
27      Manon
28      Sarah
29      Julie
30      Julie
31    Antoine
32    Nicolas
33      Sarah
34     Maxime
Name: Name, dtype: object

In [170]:
df_1.iloc[2]

Name        Camille
Age              69
City    Montpellier
Name: 2, dtype: object

In [171]:
df_1[df_1['Age']>25].head(5)

      Name  Age         City
0   Thomas   58         Lyon
1    Sarah   37       Nantes
2  Camille   69  Montpellier
4  Antoine   91         Nice
6   Thomas   75         Lyon

In [172]:
"""
Sorting and Ranking:
Sort the DataFrame based on 'Age' in descending order.
Create a variable 'Age_rank', with the oldest as rank 1.
"""

df_1_sorted=df_1.sort_values('Age', ascending=False)
age_rank=df_1_sorted['Age'].rank(ascending=False, method='min')
df_1_sorted['Age rank']=age_rank
pd.concat((df_1, df_1_sorted['Age rank']),axis=1)

       Name  Age         City  Age rank
0    Thomas   58         Lyon      14.0
1     Sarah   37       Nantes      20.0
2   Camille   69  Montpellier      10.0
3    Thomas   15        Lille      29.0
4   Antoine   91         Nice       1.0
5   Nicolas   13     Bordeaux      32.0
6    Thomas   75         Lyon       5.0
7   Antoine   56  Montpellier      17.0
8     Sarah   15        Lille      29.0
9   Antoine   31         Lyon      24.0
10    Julie   43        Paris      19.0
11    Lucas   79        Lille       3.0
12   Maxime   49         Lyon      18.0
13    Lucas   16   Strasbourg      28.0
14  Camille   19         Nice      27.0
15  Antoine   62        Lille      12.0
16    Lucas    9  Montpellier      34.0
17    Sarah   66        Paris      11.0
18    Julie   57         Lyon      16.0
19   Maxime    3   Strasbourg      35.0
20    Chloé   26         Nice      25.0
21    Chloé   35    Marseille      21.0
22    Lucas   72  Montpellier       8.0
23   Thomas   10    Marseille      33.0
24  Camille   15       Nantes      29.0
25  Antoine   78        Lille       4.0
26    Julie   25       Nantes      26.0
27    Manon   34       Nantes      23.0
28    Sarah   75         Lyon       5.0
29    Julie   58        Paris      14.0
30    Julie   59         Lyon      13.0
31  Antoine   35         Nice      21.0
32  Nicolas   75         Lyon       5.0
33    Sarah   86     Bordeaux       2.0
34   Maxime   72        Lille       8.0

In [173]:
"""
Missing Data:
Introduce some missing values in the DataFrame using np.nan.
Create a dataframe using a dictionnary by comprehension
Do not add missing values to the column Name
Display the number of missing values for each columns
Fill the missing values with the mean of the non-missing values.
"""
df_2=df_1.copy()
df_2['Age'].iloc[4:11]=np.nan
df_2['Age']=df_1['Age'].fillna(df_2['Age'].mean())
df_2

/tmp/ipykernel_3451/4252738240.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_1['Age'].iloc[4:11]=np.nan
/tmp/ipykernel_3451/4252738240.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['Age'].iloc[4:11]=np.nan

       Name        Age         City
0    Thomas  58.000000         Lyon
1     Sarah  37.000000       Nantes
2   Camille  69.000000  Montpellier
3    Thomas  15.000000        Lille
4   Antoine  46.214286         Nice
5   Nicolas  46.214286     Bordeaux
6    Thomas  46.214286         Lyon
7   Antoine  46.214286  Montpellier
8     Sarah  46.214286        Lille
9   Antoine  46.214286         Lyon
10    Julie  46.214286        Paris
11    Lucas  79.000000        Lille
12   Maxime  49.000000         Lyon
13    Lucas  16.000000   Strasbourg
14  Camille  19.000000         Nice
15  Antoine  62.000000        Lille
16    Lucas   9.000000  Montpellier
17    Sarah  66.000000        Paris
18    Julie  57.000000         Lyon
19   Maxime   3.000000   Strasbourg
20    Chloé  26.000000         Nice
21    Chloé  35.000000    Marseille
22    Lucas  72.000000  Montpellier
23   Thomas  10.000000    Marseille
24  Camille  15.000000       Nantes
25  Antoine  78.000000        Lille
26    Julie  25.000000       Nantes
27    Manon  34.000000       Nantes
28    Sarah  75.000000         Lyon
29    Julie  58.000000        Paris
30    Julie  59.000000         Lyon
31  Antoine  35.000000         Nice
32  Nicolas  75.000000         Lyon
33    Sarah  86.000000     Bordeaux
34   Maxime  72.000000        Lille

In [175]:
"""
Grouping and Aggregation:
Group the DataFrame by 'City' and calculate the mean age for each city.
Find the maximum and minimum age for each city.
Create a variable 'Age_rank_by_city', creating a ranking for each city.
"""
df_1

       Name        Age         City
0    Thomas  58.000000         Lyon
1     Sarah  37.000000       Nantes
2   Camille  69.000000  Montpellier
3    Thomas  15.000000        Lille
4   Antoine  46.214286         Nice
5   Nicolas  46.214286     Bordeaux
6    Thomas  46.214286         Lyon
7   Antoine  46.214286  Montpellier
8     Sarah  46.214286        Lille
9   Antoine  46.214286         Lyon
10    Julie  46.214286        Paris
11    Lucas  79.000000        Lille
12   Maxime  49.000000         Lyon
13    Lucas  16.000000   Strasbourg
14  Camille  19.000000         Nice
15  Antoine  62.000000        Lille
16    Lucas   9.000000  Montpellier
17    Sarah  66.000000        Paris
18    Julie  57.000000         Lyon
19   Maxime   3.000000   Strasbourg
20    Chloé  26.000000         Nice
21    Chloé  35.000000    Marseille
22    Lucas  72.000000  Montpellier
23   Thomas  10.000000    Marseille
24  Camille  15.000000       Nantes
25  Antoine  78.000000        Lille
26    Julie  25.000000       Nantes
27    Manon  34.000000       Nantes
28    Sarah  75.000000         Lyon
29    Julie  58.000000        Paris
30    Julie  59.000000         Lyon
31  Antoine  35.000000         Nice
32  Nicolas  75.000000         Lyon
33    Sarah  86.000000     Bordeaux
34   Maxime  72.000000        Lille